apiVersion: v1
kind: ServiceAccount
metadata:
  name: pharos-api
  labels:
    app.kubernetes.io/name: pharos
    app.kubernetes.io/component: api
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
